name: Deploy FastAPI to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt # Adjust based on your setup

    - name: Build FastAPI application
      run: |
        mkdir dist
        uvicorn main:app --host 0.0.0.0 --port 8000 &
        sleep 10 
        wget http://localhost:8000/docs -O dist/docs.html

    - name: Create or switch to gh-pages branch
      run: |
        git checkout -B gh-pages

    - name: Deploy to GitHub Pages
      run: |
        mkdir gh-pages
        mv dist/* gh-pages/
        rm -rf *
        mv gh-pages/* .
        git add .
        git commit -m "Deploy FastAPI to GitHub Pages"
        git push origin gh-pages
